# Generated by Django 3.1.3 on 2020-11-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='guest_name',
            new_name='name',
        ),
    ]
